django2/news/apps/news/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from .views import IndexView
from .views import NewsView, NewsItemView
from .views import RegisterView
from .views import UserProfileView
from .views import CalculatorView
from .views import LoginView
from .views import JsonCreateComment, JsonGetComments
from .views import JsonGetNewsTitles, JsonGetNewsItem
from .views import JsonCreateDeleteBookmark, JsonGetBookmarks
from .views import OnePageApplication
from editor.views import NewsUpdateView, NewsCreateView
from editor.views import EditorProfileView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tax_api/', include("tax_api.urls")),
    url(r'^calculator/$', CalculatorView.as_view(), name="calculator_url"),
    url(r'^site/$', IndexView.as_view(), name="site_url"),
    url(r'^site/news/$', NewsView.as_view(), name="site_news_url"),
    url(r'^site/news/(?P<news_item>\w+)/$', NewsItemView.as_view(), name = "news_item_url"),
    url(r'^site/register/$', RegisterView.as_view(), name = "register_url"),
    url(r'^site/user/logout/$', views.logout, name = "logout_url"),
    url(r'^site/user/login/$', LoginView.as_view(), name = "login_url"),
    url(r'^site/profile/$', UserProfileView.as_view(), name ="profile_url"),
    url(r'^site/editor_profile/$', EditorProfileView.as_view(), name = "editor_profile_url"),
    url(r'^site/editor_profile/(?P<page>\d+)/$', EditorProfileView.as_view(), name = "editor_profile_page_url"),
    url(r'^site/editor_profile/add_news/$', NewsCreateView.as_view(), name = "editor_profile_add_news_url"),
    url(r'^site/editor_profile/edit_news/(?P<news_item>\w+)/$', NewsUpdateView.as_view(), name = "editor_profile_edit_news_url"),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^one_page_application/$', OnePageApplication.as_view(), name = u"one_page_application_url"),
    url(r'^content/comments/create/$', JsonCreateComment.as_view(), name = u"create_comment_url"),
    url(r'^content/comments/get_all/$', JsonGetComments.as_view(), name = u"get_all_comments_url"),
    url(r'^content/news/get_news_titles/$', JsonGetNewsTitles.as_view(), name = u"get_news_titles_url"),
    url(r'^content/news/get_news_item/$', JsonGetNewsItem.as_view(), name = u"get_news_item_url"),
    url(r'^content/bookmarks/get_all/$', JsonGetBookmarks.as_view(), name = u"get_all_bookmarks_url"),
    url(r'^content/bookmarks/create/$', JsonCreateDeleteBookmark.as_view(), name = u"create_bookmark_url"),
    url(r'^content/bookmarks/delete/$', JsonCreateDeleteBookmark.as_view(), name = u"delete_bookmark_url"),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django2/news/apps/news/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User as DjangoUser
from django.core.urlresolvers import reverse
from editor.models import Editor

from redactor.fields import RedactorField

import datetime
import re

class News(models.Model):
    name    = models.CharField(verbose_name = u'имя', max_length = 200)
    content = RedactorField(verbose_name = u"содержание", default="")
    slug    = models.SlugField(verbose_name = u'slug', unique=True)
    date_of_creating = models.DateTimeField(verbose_name = u'дата_создания', auto_now_add=True, null = True)
    date_of_editing  = models.DateTimeField(verbose_name = u'дата_изменения', auto_now=True, blank = True, null = True)
    image = models.ImageField(verbose_name = u'изображение', blank = True)
    views  = models.IntegerField(verbose_name = u'количество_просмотров', blank = True, default = 0)
    author = models.ForeignKey(Editor, null = True, blank = True, on_delete = models.CASCADE)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            generated_slug = self.author.user.username + " " + self.name
            clear_slug = "".join(re.findall("[\w\s]+", generated_slug, re.UNICODE))
            self.slug = clear_slug.replace(' ', '_')
        super(News, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("news_item_url", kwargs={"news_item": self.slug})

class Users(models.Model):
    name = models.CharField(verbose_name = u'имя', max_length = 200)
    surname = models.CharField(verbose_name = u'фамилия', max_length = 200)
    registration_date = models.DateTimeField(verbose_name = u'дата_регистрации', auto_now_add=True)

class Comments(models.Model):
    news  = models.ForeignKey(News, null = True, on_delete = models.CASCADE)
    user  = models.ForeignKey(DjangoUser, null = True, blank = True, on_delete = models.CASCADE)
    publication_date = models.DateTimeField(verbose_name = u'дата_регистрации', null = True, auto_now_add=True)
    text  = models.TextField(verbose_name = u'содержание', default="")
    communication = models.CharField(verbose_name = u'способ_связи', null=True, max_length = 200)

class Bookmark(models.Model):
    user = models.ForeignKey(DjangoUser, null = True, blank = True)
    news = models.ForeignKey(News, null = True, blank = True)

django2/news/apps/news/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render
from django.utils.timezone import utc
from django.views.generic.base import TemplateView, View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, BaseDetailView
from django.views.generic.edit import CreateView, FormView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from news.models import News, Comments, Bookmark
from news.forms import RegisterForm, CommentsModelForm, LoginModelForm
from news.forms import NewsModelForm


class IndexView(TemplateView):
    template_name = u"index.html"

class NewsView(ListView):
    model = News
    template_name = u"news.html"
    context_object_name = u"news"

class NewsItemView(DetailView):
    model = News
    context_object_name = u"news_item"
    slug_field = u"slug"
    slug_url_kwarg = u"news_item"
    template_name = u"news_item.html"
    form_class = CommentsModelForm

    def get_context_data(self, **kwargs):
        top_the_best = News.objects.all().order_by("-views")[:10]
        top_the_newest = News.objects.all().order_by("-date_of_creating")[:10]
        all_news = News.objects.all()
        top_the_most_discused = sorted(all_news, key = lambda a: a.comments_set.count(), reverse=True)

        context = super(NewsItemView, self).get_context_data(**kwargs)
        context[u"comments"] = Comments.objects.filter(news = self.get_object())
        context[u"top_the_newest"] = top_the_newest,
        context[u"top_the_best"] = top_the_best,
        context[u"top_the_most_discufed"] = top_the_most_discused,
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views += 1
        self.object.save()

        context = self.get_context_data()
        context.update({
            "comments_form": CommentsModelForm()
        })

        return render(request, self.template_name, context)


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user = request.user if request.user.is_authenticated else None;
        comments_form = CommentsModelForm(self.object, user, request.POST)

        status = u"Fail"
        if comments_form.is_valid():
            status = u"Success"
            comments_form.save()

        context = self.get_context_data()
        context.update({
            u"comments_form": comments_form,
            u"status": status,
        });

        return render(request, self.template_name, context)


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = u"register.html"

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        email    = form.cleaned_data["email"]
        User.objects.create_user(username, password=password, email=email)

        redirect_url = self.request.GET["next"]
        if redirect_url:
            return HttpResponseRedirect(redirect_url)
        else:
            return HttpResponseRedirect(reverse(u"site_url"))

class UserProfileView(TemplateView):
    template_name = u"user_profile.html"

    def get_context_data(self, **kwargs):
        user = self.request.user
        if (user.is_authenticated()):
            context = super(UserProfileView, self).get_context_data(**kwargs)
            time_since_registration = datetime.datetime.now().replace(tzinfo=None) - user.date_joined.replace(tzinfo=None)
            comments_count = user.comments_set.count()
            time_difference = datetime.datetime.utcnow().replace(tzinfo = utc) - user.date_joined
            if (time_difference.days == 0):
                comments_per_day = comments_count
            else:
                comments_per_day = comments_count / time_difference.days
            context.update({
                            "time_since_registration": time_since_registration,
                            "comments_per_day": comments_per_day,
                        })
        else:
             context = dict()
        return context


class LoginView(FormView):
    form_class = LoginModelForm
    template_name = u"login.html"
    success_url = reverse_lazy(u"site_url")

    def form_valid(self, form):
        username = form.cleaned_data["login"]
        password = form.cleaned_data["password"]
        user = authenticate(username=username, password=password)
        if user:
            login(self.request, user)
            redirect_url = self.request.GET.get('next')
            if redirect_url:
                return HttpResponseRedirect(redirect_url)
        else:
            form.add_error(None, "Invalid login or password")
            context = self.get_context_data()
            context["form"] = form
            return render(self.request, self.template_name, context)

        return super(LoginView, self).form_valid(form)


class CalculatorView(TemplateView):
    template_name = u"calculator.html";


class JsonResponseMixin(object):
    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(context, safe=False)

class JsonCreateComment(JsonResponseMixin, CreateView):
    model = Comments
    form_class = CommentsModelForm

    def form_valid(self, form):
        request = self.request
        user = request.user if request.user.is_authenticated else None;
        news_slug = request.POST.get("news_slug")
        news_item = News.objects.get(slug = news_slug)
        form = CommentsModelForm(request.POST, news_item = news_item, user = user)
        form.save()
        form_data = form.data.dict()
        form_data["author"] = user.username if user else "Anonimous"
        return self.render_to_json_response(form_data)


class JsonGetComments(JsonResponseMixin, ListView):
    def get_queryset(self):
        return [{
            "text": comment.text,
            "author": comment.user.username if comment.user else "Anonimous"
        } for comment in Comments.objects.all()]

    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(self.object_list)


class OnePageApplication(TemplateView):
    template_name = u"one_page_application.html"


class JsonGetNewsTitles(JsonResponseMixin, ListView):
    def get_queryset(self):
        return [ news_item for news_item in News.objects.values("name", "slug") ]

    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(self.object_list)


class JsonGetNewsItem(JsonResponseMixin, DetailView):
    def get_object(self, queryset=None):
        slug = self.request.GET["slug"]
        news_item = News.objects.get(slug=slug)
        user = self.request.user
        in_bookmarks = False
        if user.is_authenticated:
            in_bookmarks = Bookmark.objects.filter(news=news_item, user=user).exists()
        news_item_dict = {
            "name": news_item.name,
            "content": news_item.content,
            "in_bookmarks": in_bookmarks,
            "is_authenticated": user.is_authenticated(),
        }
        return news_item_dict

    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(self.object)

def create_bookmark_dict(bookmark):
    if (bookmark):
        return  {
            "name": bookmark.news.name,
            "slug": bookmark.news.slug,
        }
    return None

class JsonGetBookmarks(JsonResponseMixin, ListView):
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            bookmarks = Bookmark.objects.filter(user=user)
            bookmarks_dict = [create_bookmark_dict(bookmark) for bookmark in bookmarks]
            return bookmarks_dict
        return None

    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(self.object_list)

from django.core.exceptions import ObjectDoesNotExist

class JsonCreateDeleteBookmark(JsonResponseMixin, View):
    def post(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            return self.send_status(False)

        news_title = request.POST["title"]
        try:
            news_item = News.objects.get(name = news_title)
        except ObjectDoesNotExist:
            return self.send_status(False)

        action = request.POST["action"]
        if action == "create":
            return self.get_or_create_bookmark(news_item, user)
        elif action == "delete":
            return self.delete_bookmark(news_item, user)
        return self.send_status(False)

    def get_or_create_bookmark(self, news_item, user):
        new_bookmark, created = Bookmark.objects.get_or_create(
            news = news_item,
            user = user,
        )
        bookmark_dict = create_bookmark_dict(new_bookmark)
        status_dictionary = self.get_status_dictionary(True)
        bookmark_dict.update(status_dictionary)
        return self.render_to_json_response(bookmark_dict)

    def delete_bookmark(self, news_item, user):
        Bookmark.objects.filter(news=news_item, user=user).delete()
        return self.send_status(True)

    def get_status_dictionary(self, is_success):
        status_as_text = "Success" if is_success else "Fail"
        status_dictionary = {
            "status": status_as_text,
        }
        return status_dictionary

    def send_status(self, is_success):
        status_dictionary = self.get_status_dictionary(is_success)
        return self.render_to_json_response(status_dictionary)

django2/news/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    {% block includes %}{% endblock %}
</head>

<body>
    <div class="wrapper block-center">
        <div class="wrapper-header">
            {% block header %}{% endblock %}
        </div>

        <ul class="wrapper-menu">
            {% block menu %}{% endblock %}
        </ul>

        <div class="wrapper-content">
            {% block content %}{% endblock %}
        </div>

        <div class="wrapper-footer clearfix">
            {% block footer %}{% endblock %}
        </div>
    </div>
</body>

</html>

django2/news/templates/calculator.html
{% extends "normal_page.html" %}
{% load staticfiles %}

{% block content %}
<script type="text/javascript" src="{% static 'calculator.js' %}"></script>
<div class="calculator">
    <input class="calculator-argument-1" type="text">
    <input class="calculator-argument-2" type="text">
    <br>
    <button class="calculator-operation calculator-operation-addition">+</button>
    <button class="calculator-operation calculator-operation-substraction">-</button>
    <button class="calculator-operation calculator-operation-multiplication">*</button>
    <button class="calculator-operation calculator-operation-division">/</button>
    <br>
    <input class="calculator-result" type="text">
</div>
{% endblock content %}

django2/news/templates/color_changer.html
{% load staticfiles %}
<div class="color-changer">
    <script src="{% static 'color_changer.js' %}"></script>
    <button class="color-changer__button background-red"></button>
    <button class="color-changer__button background-blue"></button>
    <button class="color-changer__button background-green"></button>
    <button class="color-changer__button background-random"></button>
</div>

django2/news/templates/footer.html
<div class="footer-copyright">
    Copyright &copy; 2005 | All Rights Reserved
</div>
<div class="footer-current-datetime">
    {% now "SHORT_DATETIME_FORMAT" %}
</div>

django2/news/templates/header.html
<div class="wrapper-header-register">
    {% if request.user.is_authenticated %}
        Hi, {{ request.user.first_name|capfirst }} {{ request.user.last_name|capfirst}} !
    <a href="{% url "logout_url" %}">
        log out
    </a>
        {% if request.user.editor %}
            <a href="{% url "editor_profile_url" %}">Editor's profile</a>
        {% endif %}
    {% else %}
    <a href="{% url "login_url" %}">
        log in
    </a>
    <a href="{% url "register_url" %}">
        register
    </a>
    {% endif %}
</div>
<div class="wrapper-header-title">
    your site.com
</div>

django2/news/templates/index.html
{% extends "normal_page.html" %}
{% load staticfiles %}

{% block includes %}
<link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}">
{{ block.super }}
{% endblock includes %}

{% block content %}
<h2>Welcome</h2>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, sapien iaculis pharetra ultrices, felis magna volutpat dolor, ac dapibus ex risus et magna. Praesent eu quam nec nibh sollicitudin viverra eu at felis. Fusce sem enim, consequat id diam quis, porttitor congue enim. Vestibulum quam diam, vehicula sit amet sagittis congue, pharetra eu tortor. Proin condimentum molestie varius. Ut eu quam euismod, congue massa vitae, pharetra dolor. Nulla at ex et quam facilisis egestas. In hendrerit magna at eros aliquam facilisiss
</p>
<div class="slick-slider">
    <img src="{% static 'images/flight_over_the_country.jpg' %}">
    <img src="{% static 'images/p2.jpg' %}">
    <img src="{% static 'images/author.jpg' %}">
</div>
<h2>Lorem ipsum</h2>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, sapien iaculis pharetra ultrices, felis magna volutpat dolor, ac dapibus ex risus et magna. Praesent eu quam nec nibh sollicitudin viverra eu at felis. Fusce sem enim, consequat id diam quis, porttitor congue enim. Vestibulum quam diam, vehicula sit amet sagittis congue, pharetra eu tortor. Proin condimentum molestie varius. Ut eu quam euismod, congue massa vitae, pharetra dolor. Nulla at ex et quam facilisis egestas. In hendrerit magna at eros aliquam facilisiss
</p>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, sapien iaculis pharetra ultrices, felis magna volutpat dolor, ac dapibus ex risus et magna. Praesent eu quam nec nibh sollicitudin viverra eu at felis. Fusce sem enim, consequat id diam quis, porttitor congue enim. Vestibulum quam diam, vehicula sit amet sagittis congue, pharetra eu tortor. Proin condimentum molestie varius. Ut eu quam euismod, congue massa vitae, pharetra dolor. Nulla at ex et quam facilisis egestas. In hendrerit magna at eros aliquam facilisiss
</p>
<script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
<script>
$(document).ready(function(){
    $('.slick-slider').slick({
        "dots": true,
    });
});
</script>
{% endblock content %}

django2/news/templates/login.html
{% extends "normal_page.html" %}

{% block content %}
    <h2>Log in</h2>
    <form action="{% url "login_url" %}?next={{ request.META.HTTP_REFERER }}" method="POST">{% csrf_token %}
        <label for="login">login:</label>
        <input type="text" name="{{ form.login.name }}" placeholder="login" id="login"></input><br>
        {{ form.errors.login|default_if_none:''}} <br>

        <label for="password">password:</label>
        <input type="password" name="{{ form.password.name }}" placeholder="password" id="password"></input><br>
        {{ form.errors.password|default_if_none:''}} <br>

        <input type="submit" value="Log in"></input>
        <div class="login_error">{{ form.non_field_errors }}</div>
    </form>
{% endblock content %}

django2/news/templates/news.html
{% extends "normal_page.html" %}

{% block content %}
{% for news_item in news %}
<div class="content-item {% cycle 'background-white' 'background-grey' %}">
    <h2><a href="{% url "news_item_url" news_item.slug %}">{{ news_item.name }}</a></h2>
    <div class="content-item-info">
        <div class="content-item-info-date"> date of creation: {{ news_item.date_of_creating|date:"j/n/Y" }} </div>
    </div>
    <p>
        {{ news_item.short_content|slice:":50"|add:"..." }}
    </p>
</div>
{% endfor %}
{% endblock content %}

django2/news/templates/news_item.html
{% extends "normal_page.html" %}
{% load staticfiles %}

{% block includes %}
{{ block.super }}
<script type="text/javascript" src="{% static 'verificator.js' %}"></script>
{% endblock includes %}

{% block header %}
<div class="header-news-title">
    {{ news_item.name }}
</div>
{{ block.super }}
{% endblock header %}

{% block content %}
<h2>{{ news_item.name|upper }}</h2>
<div class="content-info">
    <div class="content-info-date"> date of creation: {{ news_item.date_of_creating|date:"j/n/Y" }} </div>
</div>
<div class="news-content">
    {% autoescape off %}
        {{ news_item.content }}
    {% endautoescape %}
</div>
<div class="news-comment">
    <form class="news-comment-form" action="javascript:void(null);" method="POST" >{% csrf_token %}
        <div>
            <input class="comment-author-name" type="text" name="{{ comments_form.username.name }}" placeholder="Имя" value="{{ comments_form.username.value|default_if_none:'' }}">
            {{ comments_form.errors.username|default_if_none:''}}
        </div>

        <div>
            <textarea oninput="recheckFieldByName('Content', getCommentFormFields)" id="comment-content" name="{{ comments_form.text.name }}" placeholder="текст">{{ comments_form.text.value|default_if_none:'' }}</textarea>
            {{ comments_form.errors.text|default_if_none:''}}
        </div>

        <div>
            <input oninput="recheckFieldByName('Phone', getCommentFormFields)" id="comment-author-phone" type="text" name="{{ comments_form.phone.name }}" placeholder="Телефон" value="{{ comments_form.phone.value|default_if_none:'' }}">
        </div>
            {{ comments_form.errors.phone|default_if_none:''}}

        <div>
            <input oninput="recheckFieldByName('Email', getCommentFormFields)" id="comment-author-email" name="{{ comments_form.email.name }}" placeholder="E-mail" value="{{ comments_form.email.value|default_if_none:''}}">
            {{ comments_form.errors.email|default_if_none:''}}
        </div>

        <input type="submit" value="Submit">
        <div class="submit-status"> {{ submit_status|default_if_none:'' }} </div>
        {{ comments_form.non_field_errors }}
    </form>
</div>
<div class="wrapper-content__about">views: {{ news_item.views }}</div>
<div class="wrapper-content__comments">
    {% for comment in comments %}
    <div class = "comment">
        {{ comment.user.username|default:'Anonimous'}}: {{ comment.text }}
    </div>
    {% endfor %}
</div>

<script type="text/javascript" src="{% static 'comment_loader.js' %}"></script>
<script type="text/javascript">
var generalNewsItemOptions = {
    createCommentUrl: "{% url 'create_comment_url' %}",
    getCommentsUrl: "{% url 'get_all_comments_url' %}",
    newsSlug: "{{ news_item.slug }}"
}

commentLoader(generalNewsItemOptions);
</script>
{% endblock content %}

django2/news/templates/normal_page.html
{% extends "base.html" %}
{% load staticfiles %}

{% block includes %}
    <link rel="stylesheet" href="{% static "style.css"%}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
{% endblock includes %}

{% block header %}
    {% include "header.html" %}
    {% include "color_changer.html" %}
{% endblock header %}

{% block menu %}
<li><a href="{% url "site_url" %}">home</a></li>
<li><a href="#">about us</a></li>
<li><a href="{% url "site_news_url" %}">news</a></li>
<li><a href="#">contact us</a></li>
<li><a href="#">links</a></li>
<li><a href="{% url "profile_url"%}">profile</a></li>
{% endblock menu %}

{% block content %}
{% endblock content %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

django2/news/templates/one_page_application.html
{% extends "normal_page.html" %}
{% load staticfiles %}

{% block content %}
<form class="one-page-application clearfix">{% csrf_token %}
    <div class="news-list">
        <div class="news-list-header clearfix">
            <a href="#" class="news-list-header-item news-list-header-item__all-news">
                Все новости
            </a>
            <a href="#" class="news-list-header-item news-list-header-item__all-bookmarks">
                Закладки
            </a>
        </div>
        <div class="news-list-body">
        </div>
    </div>
    <div class="news-item">
        <div class="news-list-header news-list-header-light clearfix">
            <div class="news-list-header-item news-list-header-item__title">
            </div>
            <a href="#" class="news-list-header-item news-list-header-item__create-bookmark">
            </a>
        </div>
        <div class="news-item-body">
        </div>
    </div>
</form>
<script type="text/javascript" src="{% static 'news_loader.js' %}"></script>
<script type="text/javascript">
    var config = {
        getNewsTitlesUrl: "{% url 'get_news_titles_url' %}",
        getNewsItemUrl: "{% url 'get_news_item_url' %}",
        getBookmarksUrl: "{% url 'get_all_bookmarks_url' %}",
        createBookmarkUrl: "{% url 'create_bookmark_url' %}",
        deleteBookmarkUrl: "{% url 'delete_bookmark_url' %}"
    };

    newsLoader(config);
</script>
{% endblock content %}

django2/news/templates/register.html
{% extends "normal_page.html" %}
{% load staticfiles %}

{% block includes %}
{{ block.super }}
 <script type="text/javascript" src="{% static 'verificator.js' %}"></script>
{% endblock includes %}

{% block content%}
<div class="wrapper-content">
    <h2>Contact us</h2>
    <p>
        <form onsubmit="return verifyRegistrationForm(this)" method="POST" action="{% url "register_url" %}?next={{ request.META.HTTP_REFERER }}">{% csrf_token %}
            <div>
                <input oninput="recheckFieldByName('Username', getRegistrationFormFields)" id="registration-username" type="text" name="{{ form.username.name }}" placeholder="Имя" value="{{ form.username.value|default_if_none:'' }}">
                {{ form.errors.username|default_if_none:''}} <br>
            </div>

            <div>
                <input oninput="recheckFieldByName('Password', getRegistrationFormFields)" id="registration-password" type="password" name="{{ form.password.name }}" placeholder="Пароль" value="{{ form.password.value|default_if_none:'' }}">
                {{ form.errors.password|default_if_none:''}} <br>
            </div>

            <div>
                <input oninput="recheckFieldByName('Phone', getRegistrationFormFields)" id="registration-phone" type="text" name="{{ form.phone_number.name }}" placeholder="Телефон" value="{{ form.phone_number.value|default_if_none:'' }}">
                {{ form.errors.phone_number|default_if_none:''}} <br>
            </div>

            <div>
                <input oninput="recheckFieldByName('Email', getRegistrationFormFields)" id="registartion-email" type="text" name="{{ form.email.name }}" placeholder="E-mail" value="{{ form.email.value|default_if_none:''}}">
                {{ form.errors.email|default_if_none:''}} <br>
            </div>

            <input type="submit" value="Registration">
            {{ comments_form.non_field_errors }}
        </form>
    </p>
</div>
{% endblock content %}

django2/news/templates/user_profile.html
{% extends "normal_page.html" %}

{% block content %}
{% if request.user.is_authenticated %}
    <h2>{{ request.user.first_name }} {{ request.user.last_name }}'s profile:</h2>
    <p>
        time since registration: {{ request.user.date_joined|timesince:""}}
    </p>
    <p>
        news created: {{ request.user.news_set.count|default:"no news" }}
    </p>
    <p>
        comments created: {{ request.user.comments_set.count|default:"no comments" }}
    </p>
    <p>
        comments per day: {{ comments_per_day }}
    </p>
    <h2>
        News:
    </h2>
    {% for news_item in request.user.news_set.all %}
        <p>
            <a href="{{ news_item.get_absolute_url }}"> {{ forloop.counter }} {{ news_item.name }}</a>
        </p>
        {% empty %}
        <p>
            You have no news.
        </p>
    {% endfor %}
{% else %}
    You are not authorized. <a href="{% url "login_url" %}">Log in</a>.
    Or <a href="{% url "register_url" %}">register</a>.
{% endif %}
{% endblock content %}